"""added users table

Revision ID: 5695106dbb3c
Revises: 
Create Date: 2015-08-28 02:46:55.689431

"""

# revision identifiers, used by Alembic.
revision = '5695106dbb3c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
